SpBundleTable = {

    ['Levels/COOP_002/COOP_002'] = {
        'levels/coop_002/coop_002',
        'levels/coop_002/ab01_art_parent',
        'levels/coop_002/ab01_parent',
        'levels/coop_002/ab02_art_parent',
        'levels/coop_002/ab02_parent',
        'levels/coop_002/ab03_art_parent',
        'levels/coop_002/ab03_parent',
        'levels/coop_002/ab04_art_parent',
        'levels/coop_002/general_sluice_ab03_parent',
    },

    ['Levels/COOP_003/COOP_003'] = {
        'levels/coop_003/coop_003',
        'levels/coop_003/ab00_art_parent',
        'levels/coop_003/ab00_art_sewer_parent',
        'levels/coop_003/ab00_parent',
        'levels/coop_003/ab00_sewer_parent',
        'levels/coop_003/ab01_art_parent',
        'levels/coop_003/ab01_parent',
        'levels/coop_003/ab02_art_parent',
        'levels/coop_003/ab02_parent',
        'levels/coop_003/ab03_parent',
    },

    ['Levels/COOP_006/COOP_006'] = {
        'levels/coop_006/coop_006',
        'levels/coop_006/ab00_vehicle_mobileaa_parent',
        'levels/coop_006/ab01_gameplaycovers_parent',
        'levels/coop_006/ab01_mortarteam_parent',
        'levels/coop_006/ab01_parent',
        'levels/coop_006/ab02_parent',
        'levels/coop_006/ab03_parent',
    },

    ['Levels/COOP_007/COOP_007'] = {
        'levels/coop_007/coop_007',
        'levels/coop_007/ab00_parent',
        'levels/coop_007/ab01_parent',
        'levels/coop_007/ab02_parent',
        'levels/coop_007/ab04_parent',
        'levels/coop_007/ab05_parent',
        'levels/coop_007/stadium_ambience',
    },

    ['Levels/COOP_009/COOP_009'] = {
        'levels/coop_009/coop_009',
        'levels/coop_009/ab00_art_interior_parent',
        'levels/coop_009/ab00_art_parent',
        'levels/coop_009/ab00_parent',
        'levels/coop_009/ab01_art_parent',
        'levels/coop_009/ab01_parent',
        'levels/coop_009/ab02_art_parent',
        'levels/coop_009/ab02_parent',
        'levels/coop_009/ab03_art_parent',
        'levels/coop_009/ab03_parent',
        --'levels/coop_009/ab_art_road_1_parent', (Crashes server for some reason)
        'levels/coop_009/ab_art_road_2_parent',
    },

    ['Levels/COOP_010/COOP_010'] = {
        'levels/coop_010/coop_010',
        'levels/coop_010/ab00_art_parent',
        'levels/coop_010/ab00_parent',
        'levels/coop_010/ab01_ab03_buffer_parent',
        'levels/coop_010/ab01_art_parent',
        'levels/coop_010/ab01_parent',
        'levels/coop_010/ab03_ab04_buffer_parent',
        'levels/coop_010/ab03_parent',
        'levels/coop_010/ab04_parent',
        'levels/coop_010/ab05_parent',
        'levels/coop_010/ab06_parent',
    },

    ['Levels/SP_Bank/SP_Bank'] = {
        'levels/sp_bank/sp_bank',
        'levels/sp_bank/assault_sub',
        'levels/sp_bank/assaultcanalprops_sub',
        'levels/sp_bank/backdrop',
        'levels/sp_bank/backdrophighway_sub',
        'levels/sp_bank/bank_sub',
        'levels/sp_bank/bmd',
        'levels/sp_bank/breach_sub',
        'levels/sp_bank/bridge_sub',
        --'levels/sp_bank/convoy_art_sub',
        'levels/sp_bank/convoy_start_sub',
        'levels/sp_bank/convoy_sub',
        'levels/sp_bank/highway_01_ambience_sub',
        'levels/sp_bank/highway_01_sub',
        'levels/sp_bank/highway_02_sub',
        'levels/sp_bank/highway_03_ambience_sub',
        --'levels/sp_bank/highway_03_props',
        'levels/sp_bank/highway_03_sub',
        'levels/sp_bank/house_art_sub',
        'levels/sp_bank/house_props_sub',
        'levels/sp_bank/house_sub',
        'levels/sp_bank/intro_sub',
        'levels/sp_bank/lightmap_01',
        'levels/sp_bank/lightmap_02',
        'levels/sp_bank/lightmap_03',
        'levels/sp_bank/lightmap_04',
        'levels/sp_bank/marines',
        'levels/sp_bank/marines2',
        'levels/sp_bank/ministry_ambience_sub',
        'levels/sp_bank/ministry_sub',
        'levels/sp_bank/passage_cutscene',
        'levels/sp_bank/passage_sub',
        --'levels/sp_bank/plaza',
        'levels/sp_bank/plaza_interior_sub',
        'levels/sp_bank/plazalightz_sub',
        'levels/sp_bank/plazaprops_sub',
        'levels/sp_bank/regroup',
        'levels/sp_bank/ride_ambience_sub',
        'levels/sp_bank/ride_sub',
        --'levels/sp_bank/tank_art_sub',
        'levels/sp_bank/tank_sub',
        'levels/sp_bank/trenchintro',
        'levels/sp_bank/vault_sub',
        'levels/sp_bank/vaultart_sub',
        'levels/sp_bank/vaultdescentanimations',
        'levels/sp_bank/vaultendanimations',
        'levels/sp_bank/vaultstream_sub',
    },

    ['Levels/SP_Earthquake/SP_Earthquake'] = {
        'levels/sp_earthquake/sp_earthquake',
        'levels/sp_earthquake/alley',
        'levels/sp_earthquake/backdrop',
        'levels/sp_earthquake/bazaar',
        'levels/sp_earthquake/bazaarfacade',
        'levels/sp_earthquake/bridgefight',
        'levels/sp_earthquake/briefing',
        'levels/sp_earthquake/building',
        'levels/sp_earthquake/cellar',
        'levels/sp_earthquake/earthquake',
        'levels/sp_earthquake/ied',
        'levels/sp_earthquake/lavscene',
        'levels/sp_earthquake/lavsceneoccluders',
        'levels/sp_earthquake/lightmap_01',
        'levels/sp_earthquake/lightmap_02',
        'levels/sp_earthquake/lightmap_03',
        'levels/sp_earthquake/meatmarket',
        'levels/sp_earthquake/parkinglot',
        'levels/sp_earthquake/parkinglotsurroundings',
        'levels/sp_earthquake/rooftop',
        'levels/sp_earthquake/rooftopextraction',
        'levels/sp_earthquake/rooftopparkour',
        'levels/sp_earthquake/rooftopsniper',
        'levels/sp_earthquake/school',
        'levels/sp_earthquake/schoolbuilding',
        'levels/sp_earthquake/stagingarea',
        'levels/sp_earthquake/stagingareasurroundings',
        'levels/sp_earthquake/stagingareawin32',
        'levels/sp_earthquake/streetcrossing',
    },

    ['Levels/SP_Earthquake2/SP_Earthquake2'] = {
        'levels/sp_earthquake2/sp_earthquake2',
        'levels/sp_earthquake2/alley_sub',
        'levels/sp_earthquake2/backdrop',
        'levels/sp_earthquake2/bazaar_sub',
        'levels/sp_earthquake2/cafe_doorsub',
        'levels/sp_earthquake2/cafe_meetmontes',
        'levels/sp_earthquake2/cafe_sub',
        --'levels/sp_earthquake2/largebuilding_sub',
        'levels/sp_earthquake2/lightmap_01',
        'levels/sp_earthquake2/lightmap_02',
        'levels/sp_earthquake2/lightmap_03',
        'levels/sp_earthquake2/meatmarket_sub',
        'levels/sp_earthquake2/parkinglot_sub',
        --'levels/sp_earthquake2/rift2_sub',
        'levels/sp_earthquake2/rift_sub',
        'levels/sp_earthquake2/school_sub',
        'levels/sp_earthquake2/solomon_intro',
        'levels/sp_earthquake2/stagingarea_bigprops',
        --'levels/sp_earthquake2/stagingarea_sub',
    },

    ['Levels/SP_Finale/SP_Finale'] = {
        'levels/sp_finale/sp_finale',
        'levels/sp_finale/chase_sub',
        'levels/sp_finale/credits',
        'levels/sp_finale/escape_sub',
        'levels/sp_finale/fight_sub',
        'levels/sp_finale/level',
        'levels/sp_finale/lightmap_01',
        'levels/sp_finale/lightmap_02',
        'levels/sp_finale/lightmap_03',
        'levels/sp_finale/lightmap_04',
        'levels/sp_finale/penn_sub',
        'levels/sp_finale/sewerart_sub',
        'levels/sp_finale/street_sub',
        'levels/sp_finale/trainride_sub',
    },

    ['Levels/SP_Jet/SP_Jet'] = {
        'levels/sp_jet/sp_jet',
        'levels/sp_jet/area_carrierlanding',
        'levels/sp_jet/area_dogfight_1',
        'levels/sp_jet/area_dogfight_2',
        'levels/sp_jet/area_fleet',
        'levels/sp_jet/area_going_home',
        'levels/sp_jet/area_highway_of_death',
        'levels/sp_jet/art_dogfightparttwo_backdrop',
        'levels/sp_jet/carrier_details',
        'levels/sp_jet/carrier_interior',
        'levels/sp_jet/carrierstart_playerandwingmananimations',
        'levels/sp_jet/dogfightpartone_backdrop',
        'levels/sp_jet/particleclouds',
    },

    ['Levels/SP_New_York/SP_New_York'] = {
        'levels/sp_new_york/sp_new_york',
        'levels/sp_new_york/level',
        'levels/sp_new_york/lightmap_01',
        'levels/sp_new_york/lightmap_02',
        'levels/sp_new_york/trainride_sub',
    },

    ['Levels/SP_Paris/SP_Paris'] = {
        'levels/sp_paris/sp_paris',
        'levels/sp_paris/backdropbuildingsclose',
        'levels/sp_paris/backdropbuildingsfar',
        'levels/sp_paris/chase',
        'levels/sp_paris/chaseintro',
        'levels/sp_paris/corridorcorner',
        'levels/sp_paris/corridorsluice',
        'levels/sp_paris/gaseventsluice',
        'levels/sp_paris/heat',
        'levels/sp_paris/heat_pc_only',
        'levels/sp_paris/lightmap_01',
        'levels/sp_paris/lightmap_02',
        'levels/sp_paris/lightmap_03',
        'levels/sp_paris/lobby',
        'levels/sp_paris/loweroffice',
        'levels/sp_paris/loweroffice_pc',
        'levels/sp_paris/parkingdeck',
        'levels/sp_paris/parkingdeckgate',
        'levels/sp_paris/parkingdeckgate_pc',
        'levels/sp_paris/rail',
        'levels/sp_paris/railbackdrop',
        'levels/sp_paris/street',
        'levels/sp_paris/tradingfloor',
        'levels/sp_paris/upperoffice',
        'levels/sp_paris/upperoffice_pc',
    },

    ['Levels/SP_Sniper/SP_Sniper'] = {
        'levels/sp_sniper/sp_sniper',
        'levels/sp_sniper/albashirstrike',
        'levels/sp_sniper/albashirstrikeart',
        'levels/sp_sniper/albashirstrikeart_pc',
        'levels/sp_sniper/background_01',
        'levels/sp_sniper/background_02',
        'levels/sp_sniper/background_persistant',
        --'levels/sp_sniper/backstreets',
        'levels/sp_sniper/briefing',
        'levels/sp_sniper/failknife',
        'levels/sp_sniper/mall',
        'levels/sp_sniper/mall_behindstreet',
        'levels/sp_sniper/mall_exterior',
        'levels/sp_sniper/mall_exterior_pc',
        'levels/sp_sniper/mall_pc',
        'levels/sp_sniper/malldefence',
        'levels/sp_sniper/malldefence_animation1',
        'levels/sp_sniper/malldefence_animation2',
        'levels/sp_sniper/malldefence_animation3',
        'levels/sp_sniper/malldefence_animation4',
        'levels/sp_sniper/malldefence_animation5',
        'levels/sp_sniper/mannequinroom',
        'levels/sp_sniper/missile',
        'levels/sp_sniper/overwatch',
        'levels/sp_sniper/plaza',
        'levels/sp_sniper/reconnest',
        'levels/sp_sniper/reconnest_pc',
        'levels/sp_sniper/rocketapartment',
        'levels/sp_sniper/sewers',
    },

    ['Levels/SP_Tank/SP_Tank'] = {
        'levels/sp_tank/sp_tank',
        'levels/sp_tank/backdrop',
        'levels/sp_tank/desertfort',
        'levels/sp_tank/desertfortpconly',
        'levels/sp_tank/desertfortsmallobjects_01_levelart',
        'levels/sp_tank/desertintro',
        'levels/sp_tank/highwayofdeath',
        'levels/sp_tank/highwayofdeath2',
        'levels/sp_tank/highwayoverpass_01',
        'levels/sp_tank/highwayoverpass_01_levelart_substream_01',
        'levels/sp_tank/highwaytoteheran_01',
        'levels/sp_tank/highwaytoteheran_02',
        'levels/sp_tank/miclic-highwaytoteheran',
        'levels/sp_tank/miclic',
        'levels/sp_tank/miclicart',
        'levels/sp_tank/roadtodesert_01',
    },

    ['Levels/SP_Tank_b/SP_Tank_b'] = {
        'levels/sp_tank_b/sp_tank_b',
        'levels/sp_tank_b/ambush',
        'levels/sp_tank_b/bankplaza_01',
        'levels/sp_tank_b/bankplazabackdrop',
        'levels/sp_tank_b/blockedstreet',
        'levels/sp_tank_b/blockedstreet2',
        'levels/sp_tank_b/drivethrough',
        'levels/sp_tank_b/drivetobankplaza_01',
        'levels/sp_tank_b/drivetobankplaza_03',
        'levels/sp_tank_b/introrail',
        'levels/sp_tank_b/lightmap_01',
        'levels/sp_tank_b/lightmap_02',
        'levels/sp_tank_b/lightmap_03',
        'levels/sp_tank_b/outroscene',
        'levels/sp_tank_b/sidestreet',
    },

    ['Levels/SP_Valley/SP_Valley'] = {
        'levels/sp_valley/sp_valley',
        'levels/sp_valley/airdrop',
        'levels/sp_valley/ambientwar',
        'levels/sp_valley/briefingonhill',
        'levels/sp_valley/forest',
        'levels/sp_valley/forestart',
        'levels/sp_valley/hillside',
        'levels/sp_valley/ridge',
        'levels/sp_valley/rundownhill',
        'levels/sp_valley/valley',
        'levels/sp_valley/valleyadvancetobridge',
        'levels/sp_valley/valleyart',
        'levels/sp_valley/valleyartillerycamp',
        'levels/sp_valley/valleyfield1',
        'levels/sp_valley/valleyfield2',
        'levels/sp_valley/valleyjet',
        'levels/sp_valley/valleyjet_endscene',
        'levels/sp_valley/valleyjetbriefing',
        'levels/sp_valley/valleytankbattle',
        'levels/sp_valley/valleytankbriefing',
        'levels/sp_valley/zone1',
        'levels/sp_valley/zone2',
        'levels/sp_valley/zone3',
        'levels/sp_valley/zone4',
        'levels/sp_valley/zone5',
    },

    ['Levels/SP_Villa/SP_Villa'] = {
        'levels/sp_villa/sp_villa',
        'levels/sp_villa/background',
        'levels/sp_villa/basement',
        'levels/sp_villa/blackburn',
        'levels/sp_villa/chopper',
        'levels/sp_villa/drive',
        'levels/sp_villa/drive_2',
        'levels/sp_villa/drive_pc',
        'levels/sp_villa/garden',
        'levels/sp_villa/garden_pc',
        'levels/sp_villa/gatehouse',
        'levels/sp_villa/halo',
        'levels/sp_villa/halo_backdrop',
        'levels/sp_villa/landing',
        'levels/sp_villa/lightmap_01',
        'levels/sp_villa/lightmap_02',
        'levels/sp_villa/lightmap_03',
        'levels/sp_villa/lightmap_cutscene01',
        'levels/sp_villa/lightmap_cutscene02',
        'levels/sp_villa/poolhouse',
        'levels/sp_villa/poolhouse_extra',
        'levels/sp_villa/rail',
        'levels/sp_villa/railsuv',
        'levels/sp_villa/villa',
        'levels/sp_villa/villa_extra',
        'levels/sp_villa/villa_pc',
    },

}